apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ packageJson.name }}-{{group}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ packageJson.name }}-{{group}}
  template:
    metadata:
      labels:
        app: {{ packageJson.name }}-{{group}}
    spec:
      hostname: {{packageJson.name}}
      # initContainers:
      #   - name: gen-keypair
      #     image: "paulczar/omgwtfssl:latest"
      #     env:
      #       - name: SSL_SUBJECT
      #         value: "{{ domain }}"
      #     volumeMounts:
      #       - mountPath: /certs
      #         name: temp-ssl
      containers:
        - name: {{ packageJson.name }}
          image: us-central1-docker.pkg.dev/{{ projectId }}/bizi-docker-images/{{ packageJson.name}}:{{tag}}
          ports:
            {{#each ports}}
            - name: port-{{this}}
              protocol: TCP
              containerPort: {{this}}
            {{/each}}
          env:
          {{#forEach environmentVariables}}
            - name: {{ key }}
              value: "{{ value }}" # substitutes with _ENV_VAR from cloudbuild.yaml
          {{/forEach}}