apiVersion: v1
kind: Service
metadata:
  name: {{packageJson.name}}
spec:
  type: LoadBalancer
  loadBalancerIP: {{loadBalancerIp}}
  selector:
    app: {{packageJson.name}}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  # - name: https
  #   protocol: TCP
  #   port: 443
  #   targetPort: 443