apiVersion: v1
kind: Service
metadata:
  name: {{packageJson.name}}
  annotations:
    cloud.google.com/l4-rbs: "enabled"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: {{loadBalancerIp}}
  selector:
    app: {{packageJson.name}}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443