apiVersion: v1
kind: Service
metadata:
  name: {{packageJson.name}}
spec:
  type: NodePort
  selector:
    app: {{packageJson.name}}
  ports:
  - protocol: TCP
    port: 30001
    targetPort: 30001
    nodePort: 30001