apiVersion: v1
kind: Service
metadata:
  name: {{packageJson.name}}-{{group}}
  # annotations:
    # cloud.google.com/l4-rbs: "enabled"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: {{loadBalancerIp}}
  selector:
    app: {{packageJson.name}}
  ports:
  {{#each ports}}
  - name: port-{{@index}}
    protocol: TCP
    port: {{port}}
    targetPort: {{port}}
  {{/each}}